jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Mzg2NDMxNjF9.h_3f6JUFCx3-75xahBK52r5tg_LPLaYDvFxM-x3evGg

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "amanda hale",
  "email": "amanda@test.com",
  "password": "password",
  "password_confirmation": "password"
}

###

POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "amanda@test.com",
  "password": "password"
}
###

GET http://localhost:3000/positions.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2MzkzNTY2MzZ9.oH5SJpNioLajAfmtAdtIcv9LPiqk1kqAq-tz30m7UCU
Content-Type: application/json

###

POST http://localhost:3000/positions.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2MzkzNTY2MzZ9.oH5SJpNioLajAfmtAdtIcv9LPiqk1kqAq-tz30m7UCU
Content-Type: application/json

{
  "asset": "DOGEUSDT",
  "amount": 100
}

###

PATCH http://localhost:3000/positions/5.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2Mzg2NDYwMzB9.x2G5e4x-2BG5YqPlzb3y7SRYitV2cW6jHezvb7aqgH4
Content-Type: application/json

{
  "asset": "BTC",
  "amount": 2
}

###

DELETE http://localhost:3000/positions/2.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2Mzg2NDYwMzB9.x2G5e4x-2BG5YqPlzb3y7SRYitV2cW6jHezvb7aqgH4
Content-Type: application/json