### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

###

POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}
###

GET http://localhost:3000/positions.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzgzMjgyMTV9.dg2bkYOd2PekEdpYFLdHLGFdR_8jHUiGCgf5AOgeXH8
Content-Type: application/json

###

POST http://localhost:3000/positions.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzgzMjgyMTV9.dg2bkYOd2PekEdpYFLdHLGFdR_8jHUiGCgf5AOgeXH8
Content-Type: application/json

{
  "asset": "BTC",
  "amount": 3
}